package com.marquess.demo.dao;

import com.marquess.demo.model.RefundResult;
import com.marquess.demo.model.RefundResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefundResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    long countByExample(RefundResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int deleteByExample(RefundResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int insert(RefundResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int insertSelective(RefundResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    List<RefundResult> selectByExample(RefundResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    RefundResult selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") RefundResult record, @Param("example") RefundResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int updateByExample(@Param("record") RefundResult record, @Param("example") RefundResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int updateByPrimaryKeySelective(RefundResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    int updateByPrimaryKey(RefundResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<RefundResult> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table refund_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<RefundResult> list, @Param("selective") RefundResult.Column ... selective);
}