server:
    tomcat:
      uri-encoding: UTF-8
    port: 6001
    context-path: /demo

spring:
    datasource:
       driver-class-name : com.mysql.jdbc.Driver
       url : jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&jdbcCompliantTruncation=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
       username : root
       password : root
       type : com.alibaba.druid.pool.DruidDataSource
       druid:
            initial-size : 20
            min-idle : 1
            max-active : 500
            max-wait : 60000
            time-between-eviction-runs-millis : 60000
            min-evictable-idle-time-millis : 300000
            max-evictable-idle-time-millis : 300000
            validation-query : SELECT 1
            validation-query-timeout : 30000
            test-while-idle : true
            test-on-borrow : false
            test-on-return : false
            pool-prepared-statements : false
            max-pool-prepared-statement-per-connection-size : 20
            max-open-prepared-statements : 20
            filters : stat,slf4j
            filter:
              slf4j:
                enabled: true
                statement-executable-sql-log-enable: true
    session:
        store-type: none
    jackson:
      date-format: "yyyy-MM-dd HH:mm:ss"
      time-zone: "GMT+08"
      default-property-inclusion: non_null
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
    mvc:
      throw-exception-if-no-handler-found: true #出现 404 错误时, 直接抛出异常
    resources:
      add-mappings: false  #不要为我们工程中的资源文件建立映射
    rabbitmq:
      host: 114.116.129.46
      #host: 127.0.0.1
      port: 5672
      #username: guest
      #password: guest
      username: admin
      password: admin
      publisher-confirms: true
      virtual-host: /
#    redis:
#      database: 0
#      host: 127.0.0.1
#      port: 6379
#      password:
#      pool:
#        max-active: 8
#        max-idel: 8
#        max-wait: -1
#        min-idle: 0
#  ## ssa
mybatis:
     mapper-locations: classpath*:mapper/com/marquess/demo/dao/*.xml
