package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.Arrays;

public class CrmTransfer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.order_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.card_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.order_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.sku_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String skuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.product_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.card_date
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String cardDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.card_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer cardStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.is_notify_crm
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer isNotifyCrm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.note
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.case_qty
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer caseQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.price
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.discount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.user_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.dnum
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String dnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.device_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String deviceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.client_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String clientType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.mac
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String mac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.cp_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String cpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.attempt_count
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer attemptCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.attempt_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String attemptTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_transfer.uuid
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String uuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.id
     *
     * @return the value of crm_transfer.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.id
     *
     * @param id the value for crm_transfer.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.trade_no
     *
     * @return the value of crm_transfer.trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.trade_no
     *
     * @param tradeNo the value for crm_transfer.trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.order_type
     *
     * @return the value of crm_transfer.order_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.order_type
     *
     * @param orderType the value for crm_transfer.order_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.card_no
     *
     * @return the value of crm_transfer.card_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.card_no
     *
     * @param cardNo the value for crm_transfer.card_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.order_time
     *
     * @return the value of crm_transfer.order_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.order_time
     *
     * @param orderTime the value for crm_transfer.order_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.sku_code
     *
     * @return the value of crm_transfer.sku_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.sku_code
     *
     * @param skuCode the value for crm_transfer.sku_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.product_code
     *
     * @return the value of crm_transfer.product_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.product_code
     *
     * @param productCode the value for crm_transfer.product_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.card_date
     *
     * @return the value of crm_transfer.card_date
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getCardDate() {
        return cardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.card_date
     *
     * @param cardDate the value for crm_transfer.card_date
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCardDate(String cardDate) {
        this.cardDate = cardDate == null ? null : cardDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.card_status
     *
     * @return the value of crm_transfer.card_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getCardStatus() {
        return cardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.card_status
     *
     * @param cardStatus the value for crm_transfer.card_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCardStatus(Integer cardStatus) {
        this.cardStatus = cardStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.is_notify_crm
     *
     * @return the value of crm_transfer.is_notify_crm
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getIsNotifyCrm() {
        return isNotifyCrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.is_notify_crm
     *
     * @param isNotifyCrm the value for crm_transfer.is_notify_crm
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setIsNotifyCrm(Integer isNotifyCrm) {
        this.isNotifyCrm = isNotifyCrm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.note
     *
     * @return the value of crm_transfer.note
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.note
     *
     * @param note the value for crm_transfer.note
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.case_qty
     *
     * @return the value of crm_transfer.case_qty
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getCaseQty() {
        return caseQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.case_qty
     *
     * @param caseQty the value for crm_transfer.case_qty
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCaseQty(Integer caseQty) {
        this.caseQty = caseQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.price
     *
     * @return the value of crm_transfer.price
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.price
     *
     * @param price the value for crm_transfer.price
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.discount
     *
     * @return the value of crm_transfer.discount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.discount
     *
     * @param discount the value for crm_transfer.discount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.user_id
     *
     * @return the value of crm_transfer.user_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.user_id
     *
     * @param userId the value for crm_transfer.user_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.dnum
     *
     * @return the value of crm_transfer.dnum
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getDnum() {
        return dnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.dnum
     *
     * @param dnum the value for crm_transfer.dnum
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setDnum(String dnum) {
        this.dnum = dnum == null ? null : dnum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.device_id
     *
     * @return the value of crm_transfer.device_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.device_id
     *
     * @param deviceId the value for crm_transfer.device_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.client_type
     *
     * @return the value of crm_transfer.client_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.client_type
     *
     * @param clientType the value for crm_transfer.client_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.mac
     *
     * @return the value of crm_transfer.mac
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getMac() {
        return mac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.mac
     *
     * @param mac the value for crm_transfer.mac
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setMac(String mac) {
        this.mac = mac == null ? null : mac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.cp_code
     *
     * @return the value of crm_transfer.cp_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getCpCode() {
        return cpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.cp_code
     *
     * @param cpCode the value for crm_transfer.cp_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCpCode(String cpCode) {
        this.cpCode = cpCode == null ? null : cpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.attempt_count
     *
     * @return the value of crm_transfer.attempt_count
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getAttemptCount() {
        return attemptCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.attempt_count
     *
     * @param attemptCount the value for crm_transfer.attempt_count
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setAttemptCount(Integer attemptCount) {
        this.attemptCount = attemptCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.attempt_time
     *
     * @return the value of crm_transfer.attempt_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getAttemptTime() {
        return attemptTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.attempt_time
     *
     * @param attemptTime the value for crm_transfer.attempt_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setAttemptTime(String attemptTime) {
        this.attemptTime = attemptTime == null ? null : attemptTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_transfer.uuid
     *
     * @return the value of crm_transfer.uuid
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_transfer.uuid
     *
     * @param uuid the value for crm_transfer.uuid
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table crm_transfer
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        tradeNo("trade_no", "tradeNo", "VARCHAR", false),
        orderType("order_type", "orderType", "INTEGER", false),
        cardNo("card_no", "cardNo", "VARCHAR", false),
        orderTime("order_time", "orderTime", "VARCHAR", false),
        skuCode("sku_code", "skuCode", "VARCHAR", false),
        productCode("product_code", "productCode", "VARCHAR", false),
        cardDate("card_date", "cardDate", "VARCHAR", false),
        cardStatus("card_status", "cardStatus", "INTEGER", false),
        isNotifyCrm("is_notify_crm", "isNotifyCrm", "INTEGER", false),
        note("note", "note", "VARCHAR", false),
        caseQty("case_qty", "caseQty", "INTEGER", false),
        price("price", "price", "INTEGER", false),
        discount("discount", "discount", "INTEGER", false),
        userId("user_id", "userId", "VARCHAR", false),
        dnum("dnum", "dnum", "VARCHAR", false),
        deviceId("device_id", "deviceId", "VARCHAR", false),
        clientType("client_type", "clientType", "VARCHAR", false),
        mac("mac", "mac", "VARCHAR", false),
        cpCode("cp_code", "cpCode", "VARCHAR", false),
        attemptCount("attempt_count", "attemptCount", "INTEGER", false),
        attemptTime("attempt_time", "attemptTime", "VARCHAR", false),
        uuid("uuid", "uuid", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table crm_transfer
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}