package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.activity_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.activity_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long activityNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.bought_copies
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer boughtCopies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.update_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.source
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.business_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String businessType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.title
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.content
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goods_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.product_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.bank
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.handle_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Date handleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.pay_amount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long payAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.employee_name
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.employee_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String employeeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.nickname
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private byte[] nickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_no
     *
     * @return the value of order.order_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_no
     *
     * @param orderNo the value for order.order_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.out_trade_no
     *
     * @return the value of order.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.out_trade_no
     *
     * @param outTradeNo the value for order.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.activity_id
     *
     * @return the value of order.activity_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.activity_id
     *
     * @param activityId the value for order.activity_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.activity_no
     *
     * @return the value of order.activity_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getActivityNo() {
        return activityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.activity_no
     *
     * @param activityNo the value for order.activity_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setActivityNo(Long activityNo) {
        this.activityNo = activityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.bought_copies
     *
     * @return the value of order.bought_copies
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getBoughtCopies() {
        return boughtCopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.bought_copies
     *
     * @param boughtCopies the value for order.bought_copies
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setBoughtCopies(Integer boughtCopies) {
        this.boughtCopies = boughtCopies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.create_time
     *
     * @return the value of order.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.create_time
     *
     * @param createTime the value for order.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.update_time
     *
     * @return the value of order.update_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.update_time
     *
     * @param updateTime the value for order.update_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.source
     *
     * @return the value of order.source
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.source
     *
     * @param source the value for order.source
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.business_type
     *
     * @return the value of order.business_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getBusinessType() {
        return businessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.business_type
     *
     * @param businessType the value for order.business_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setBusinessType(String businessType) {
        this.businessType = businessType == null ? null : businessType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.title
     *
     * @return the value of order.title
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.title
     *
     * @param title the value for order.title
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.content
     *
     * @return the value of order.content
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.content
     *
     * @param content the value for order.content
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goods_id
     *
     * @return the value of order.goods_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goods_id
     *
     * @param goodsId the value for order.goods_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.product_id
     *
     * @return the value of order.product_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.product_id
     *
     * @param productId the value for order.product_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.bank
     *
     * @return the value of order.bank
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.bank
     *
     * @param bank the value for order.bank
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_time
     *
     * @return the value of order.pay_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_time
     *
     * @param payTime the value for order.pay_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setPayTime(String payTime) {
        this.payTime = payTime == null ? null : payTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.handle_time
     *
     * @return the value of order.handle_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Date getHandleTime() {
        return handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.handle_time
     *
     * @param handleTime the value for order.handle_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setHandleTime(Date handleTime) {
        this.handleTime = handleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.pay_amount
     *
     * @return the value of order.pay_amount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.pay_amount
     *
     * @param payAmount the value for order.pay_amount
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setPayAmount(Long payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.employee_name
     *
     * @return the value of order.employee_name
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.employee_name
     *
     * @param employeeName the value for order.employee_name
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.employee_no
     *
     * @return the value of order.employee_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.employee_no
     *
     * @param employeeNo the value for order.employee_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo == null ? null : employeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_type
     *
     * @return the value of order.order_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_type
     *
     * @param orderType the value for order.order_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOrderType(Integer orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.nickname
     *
     * @return the value of order.nickname
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public byte[] getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.nickname
     *
     * @param nickname the value for order.nickname
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setNickname(byte[] nickname) {
        this.nickname = nickname;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        orderNo("order_no", "orderNo", "VARCHAR", false),
        outTradeNo("out_trade_no", "outTradeNo", "VARCHAR", false),
        activityId("activity_id", "activityId", "BIGINT", false),
        activityNo("activity_no", "activityNo", "BIGINT", false),
        status("status", "status", "INTEGER", false),
        amount("amount", "amount", "INTEGER", false),
        boughtCopies("bought_copies", "boughtCopies", "INTEGER", false),
        userId("user_id", "userId", "BIGINT", false),
        createTime("create_time", "createTime", "BIGINT", false),
        updateTime("update_time", "updateTime", "TIMESTAMP", false),
        source("source", "source", "VARCHAR", false),
        businessType("business_type", "businessType", "VARCHAR", false),
        title("title", "title", "VARCHAR", false),
        content("content", "content", "VARCHAR", false),
        goodsId("goods_id", "goodsId", "BIGINT", false),
        productId("product_id", "productId", "BIGINT", false),
        bank("bank", "bank", "VARCHAR", false),
        payTime("pay_time", "payTime", "VARCHAR", false),
        handleTime("handle_time", "handleTime", "TIMESTAMP", false),
        payAmount("pay_amount", "payAmount", "BIGINT", false),
        employeeName("employee_name", "employeeName", "VARCHAR", false),
        employeeNo("employee_no", "employeeNo", "VARCHAR", false),
        orderType("order_type", "orderType", "INTEGER", false),
        nickname("nickname", "nickname", "BINARY", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table order
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}