package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductDescIsNull() {
            addCriterion("product_desc is null");
            return (Criteria) this;
        }

        public Criteria andProductDescIsNotNull() {
            addCriterion("product_desc is not null");
            return (Criteria) this;
        }

        public Criteria andProductDescEqualTo(String value) {
            addCriterion("product_desc =", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotEqualTo(String value) {
            addCriterion("product_desc <>", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescGreaterThan(String value) {
            addCriterion("product_desc >", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescGreaterThanOrEqualTo(String value) {
            addCriterion("product_desc >=", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLessThan(String value) {
            addCriterion("product_desc <", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLessThanOrEqualTo(String value) {
            addCriterion("product_desc <=", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescLike(String value) {
            addCriterion("product_desc like", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotLike(String value) {
            addCriterion("product_desc not like", value, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescIn(List<String> values) {
            addCriterion("product_desc in", values, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotIn(List<String> values) {
            addCriterion("product_desc not in", values, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescBetween(String value1, String value2) {
            addCriterion("product_desc between", value1, value2, "productDesc");
            return (Criteria) this;
        }

        public Criteria andProductDescNotBetween(String value1, String value2) {
            addCriterion("product_desc not between", value1, value2, "productDesc");
            return (Criteria) this;
        }

        public Criteria andHomePicIsNull() {
            addCriterion("home_pic is null");
            return (Criteria) this;
        }

        public Criteria andHomePicIsNotNull() {
            addCriterion("home_pic is not null");
            return (Criteria) this;
        }

        public Criteria andHomePicEqualTo(String value) {
            addCriterion("home_pic =", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicNotEqualTo(String value) {
            addCriterion("home_pic <>", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicGreaterThan(String value) {
            addCriterion("home_pic >", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicGreaterThanOrEqualTo(String value) {
            addCriterion("home_pic >=", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicLessThan(String value) {
            addCriterion("home_pic <", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicLessThanOrEqualTo(String value) {
            addCriterion("home_pic <=", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicLike(String value) {
            addCriterion("home_pic like", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicNotLike(String value) {
            addCriterion("home_pic not like", value, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicIn(List<String> values) {
            addCriterion("home_pic in", values, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicNotIn(List<String> values) {
            addCriterion("home_pic not in", values, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicBetween(String value1, String value2) {
            addCriterion("home_pic between", value1, value2, "homePic");
            return (Criteria) this;
        }

        public Criteria andHomePicNotBetween(String value1, String value2) {
            addCriterion("home_pic not between", value1, value2, "homePic");
            return (Criteria) this;
        }

        public Criteria andDetailPicIsNull() {
            addCriterion("detail_pic is null");
            return (Criteria) this;
        }

        public Criteria andDetailPicIsNotNull() {
            addCriterion("detail_pic is not null");
            return (Criteria) this;
        }

        public Criteria andDetailPicEqualTo(String value) {
            addCriterion("detail_pic =", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotEqualTo(String value) {
            addCriterion("detail_pic <>", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicGreaterThan(String value) {
            addCriterion("detail_pic >", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicGreaterThanOrEqualTo(String value) {
            addCriterion("detail_pic >=", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicLessThan(String value) {
            addCriterion("detail_pic <", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicLessThanOrEqualTo(String value) {
            addCriterion("detail_pic <=", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicLike(String value) {
            addCriterion("detail_pic like", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotLike(String value) {
            addCriterion("detail_pic not like", value, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicIn(List<String> values) {
            addCriterion("detail_pic in", values, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotIn(List<String> values) {
            addCriterion("detail_pic not in", values, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicBetween(String value1, String value2) {
            addCriterion("detail_pic between", value1, value2, "detailPic");
            return (Criteria) this;
        }

        public Criteria andDetailPicNotBetween(String value1, String value2) {
            addCriterion("detail_pic not between", value1, value2, "detailPic");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseIsNull() {
            addCriterion("video_license is null");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseIsNotNull() {
            addCriterion("video_license is not null");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseEqualTo(String value) {
            addCriterion("video_license =", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseNotEqualTo(String value) {
            addCriterion("video_license <>", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseGreaterThan(String value) {
            addCriterion("video_license >", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("video_license >=", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseLessThan(String value) {
            addCriterion("video_license <", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseLessThanOrEqualTo(String value) {
            addCriterion("video_license <=", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseLike(String value) {
            addCriterion("video_license like", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseNotLike(String value) {
            addCriterion("video_license not like", value, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseIn(List<String> values) {
            addCriterion("video_license in", values, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseNotIn(List<String> values) {
            addCriterion("video_license not in", values, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseBetween(String value1, String value2) {
            addCriterion("video_license between", value1, value2, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andVideoLicenseNotBetween(String value1, String value2) {
            addCriterion("video_license not between", value1, value2, "videoLicense");
            return (Criteria) this;
        }

        public Criteria andInputNumIsNull() {
            addCriterion("input_num is null");
            return (Criteria) this;
        }

        public Criteria andInputNumIsNotNull() {
            addCriterion("input_num is not null");
            return (Criteria) this;
        }

        public Criteria andInputNumEqualTo(Integer value) {
            addCriterion("input_num =", value, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumNotEqualTo(Integer value) {
            addCriterion("input_num <>", value, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumGreaterThan(Integer value) {
            addCriterion("input_num >", value, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("input_num >=", value, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumLessThan(Integer value) {
            addCriterion("input_num <", value, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumLessThanOrEqualTo(Integer value) {
            addCriterion("input_num <=", value, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumIn(List<Integer> values) {
            addCriterion("input_num in", values, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumNotIn(List<Integer> values) {
            addCriterion("input_num not in", values, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumBetween(Integer value1, Integer value2) {
            addCriterion("input_num between", value1, value2, "inputNum");
            return (Criteria) this;
        }

        public Criteria andInputNumNotBetween(Integer value1, Integer value2) {
            addCriterion("input_num not between", value1, value2, "inputNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumIsNull() {
            addCriterion("sold_num is null");
            return (Criteria) this;
        }

        public Criteria andSoldNumIsNotNull() {
            addCriterion("sold_num is not null");
            return (Criteria) this;
        }

        public Criteria andSoldNumEqualTo(Integer value) {
            addCriterion("sold_num =", value, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumNotEqualTo(Integer value) {
            addCriterion("sold_num <>", value, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumGreaterThan(Integer value) {
            addCriterion("sold_num >", value, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sold_num >=", value, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumLessThan(Integer value) {
            addCriterion("sold_num <", value, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumLessThanOrEqualTo(Integer value) {
            addCriterion("sold_num <=", value, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumIn(List<Integer> values) {
            addCriterion("sold_num in", values, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumNotIn(List<Integer> values) {
            addCriterion("sold_num not in", values, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumBetween(Integer value1, Integer value2) {
            addCriterion("sold_num between", value1, value2, "soldNum");
            return (Criteria) this;
        }

        public Criteria andSoldNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sold_num not between", value1, value2, "soldNum");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNull() {
            addCriterion("original_price is null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIsNotNull() {
            addCriterion("original_price is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceEqualTo(Integer value) {
            addCriterion("original_price =", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotEqualTo(Integer value) {
            addCriterion("original_price <>", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThan(Integer value) {
            addCriterion("original_price >", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("original_price >=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThan(Integer value) {
            addCriterion("original_price <", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceLessThanOrEqualTo(Integer value) {
            addCriterion("original_price <=", value, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceIn(List<Integer> values) {
            addCriterion("original_price in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotIn(List<Integer> values) {
            addCriterion("original_price not in", values, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceBetween(Integer value1, Integer value2) {
            addCriterion("original_price between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andOriginalPriceNotBetween(Integer value1, Integer value2) {
            addCriterion("original_price not between", value1, value2, "originalPrice");
            return (Criteria) this;
        }

        public Criteria andSoldStatusIsNull() {
            addCriterion("sold_status is null");
            return (Criteria) this;
        }

        public Criteria andSoldStatusIsNotNull() {
            addCriterion("sold_status is not null");
            return (Criteria) this;
        }

        public Criteria andSoldStatusEqualTo(Integer value) {
            addCriterion("sold_status =", value, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusNotEqualTo(Integer value) {
            addCriterion("sold_status <>", value, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusGreaterThan(Integer value) {
            addCriterion("sold_status >", value, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("sold_status >=", value, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusLessThan(Integer value) {
            addCriterion("sold_status <", value, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusLessThanOrEqualTo(Integer value) {
            addCriterion("sold_status <=", value, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusIn(List<Integer> values) {
            addCriterion("sold_status in", values, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusNotIn(List<Integer> values) {
            addCriterion("sold_status not in", values, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusBetween(Integer value1, Integer value2) {
            addCriterion("sold_status between", value1, value2, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andSoldStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("sold_status not between", value1, value2, "soldStatus");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNull() {
            addCriterion("product_type is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeIsNotNull() {
            addCriterion("product_type is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeEqualTo(Integer value) {
            addCriterion("product_type =", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotEqualTo(Integer value) {
            addCriterion("product_type <>", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThan(Integer value) {
            addCriterion("product_type >", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_type >=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThan(Integer value) {
            addCriterion("product_type <", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeLessThanOrEqualTo(Integer value) {
            addCriterion("product_type <=", value, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeIn(List<Integer> values) {
            addCriterion("product_type in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotIn(List<Integer> values) {
            addCriterion("product_type not in", values, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeBetween(Integer value1, Integer value2) {
            addCriterion("product_type between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andProductTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("product_type not between", value1, value2, "productType");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("supplier is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("supplier is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("supplier =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("supplier <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("supplier >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("supplier >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("supplier <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("supplier <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("supplier like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("supplier not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("supplier in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("supplier not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("supplier between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("supplier not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andCardNamesIsNull() {
            addCriterion("card_names is null");
            return (Criteria) this;
        }

        public Criteria andCardNamesIsNotNull() {
            addCriterion("card_names is not null");
            return (Criteria) this;
        }

        public Criteria andCardNamesEqualTo(String value) {
            addCriterion("card_names =", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesNotEqualTo(String value) {
            addCriterion("card_names <>", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesGreaterThan(String value) {
            addCriterion("card_names >", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesGreaterThanOrEqualTo(String value) {
            addCriterion("card_names >=", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesLessThan(String value) {
            addCriterion("card_names <", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesLessThanOrEqualTo(String value) {
            addCriterion("card_names <=", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesLike(String value) {
            addCriterion("card_names like", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesNotLike(String value) {
            addCriterion("card_names not like", value, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesIn(List<String> values) {
            addCriterion("card_names in", values, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesNotIn(List<String> values) {
            addCriterion("card_names not in", values, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesBetween(String value1, String value2) {
            addCriterion("card_names between", value1, value2, "cardNames");
            return (Criteria) this;
        }

        public Criteria andCardNamesNotBetween(String value1, String value2) {
            addCriterion("card_names not between", value1, value2, "cardNames");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 06 16:21:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}