package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_desc
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String productDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.home_pic
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String homePic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.detail_pic
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String detailPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.video_license
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String videoLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.input_num
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer inputNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sold_num
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer soldNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.original_price
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer originalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sold_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer soldStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.supplier
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.card_names
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String cardNames;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_desc
     *
     * @return the value of product.product_desc
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_desc
     *
     * @param productDesc the value for product.product_desc
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc == null ? null : productDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.home_pic
     *
     * @return the value of product.home_pic
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getHomePic() {
        return homePic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.home_pic
     *
     * @param homePic the value for product.home_pic
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setHomePic(String homePic) {
        this.homePic = homePic == null ? null : homePic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.detail_pic
     *
     * @return the value of product.detail_pic
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getDetailPic() {
        return detailPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.detail_pic
     *
     * @param detailPic the value for product.detail_pic
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setDetailPic(String detailPic) {
        this.detailPic = detailPic == null ? null : detailPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.create_time
     *
     * @return the value of product.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.create_time
     *
     * @param createTime the value for product.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.video_license
     *
     * @return the value of product.video_license
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getVideoLicense() {
        return videoLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.video_license
     *
     * @param videoLicense the value for product.video_license
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setVideoLicense(String videoLicense) {
        this.videoLicense = videoLicense == null ? null : videoLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.input_num
     *
     * @return the value of product.input_num
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getInputNum() {
        return inputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.input_num
     *
     * @param inputNum the value for product.input_num
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setInputNum(Integer inputNum) {
        this.inputNum = inputNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sold_num
     *
     * @return the value of product.sold_num
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getSoldNum() {
        return soldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sold_num
     *
     * @param soldNum the value for product.sold_num
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSoldNum(Integer soldNum) {
        this.soldNum = soldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.original_price
     *
     * @return the value of product.original_price
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getOriginalPrice() {
        return originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.original_price
     *
     * @param originalPrice the value for product.original_price
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOriginalPrice(Integer originalPrice) {
        this.originalPrice = originalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sold_status
     *
     * @return the value of product.sold_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getSoldStatus() {
        return soldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sold_status
     *
     * @param soldStatus the value for product.sold_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSoldStatus(Integer soldStatus) {
        this.soldStatus = soldStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type
     *
     * @return the value of product.product_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type
     *
     * @param productType the value for product.product_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.supplier
     *
     * @return the value of product.supplier
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.supplier
     *
     * @param supplier the value for product.supplier
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.card_names
     *
     * @return the value of product.card_names
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getCardNames() {
        return cardNames;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.card_names
     *
     * @param cardNames the value for product.card_names
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCardNames(String cardNames) {
        this.cardNames = cardNames == null ? null : cardNames.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table product
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        productName("product_name", "productName", "VARCHAR", false),
        productDesc("product_desc", "productDesc", "VARCHAR", false),
        homePic("home_pic", "homePic", "VARCHAR", false),
        detailPic("detail_pic", "detailPic", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        videoLicense("video_license", "videoLicense", "VARCHAR", false),
        inputNum("input_num", "inputNum", "INTEGER", false),
        soldNum("sold_num", "soldNum", "INTEGER", false),
        originalPrice("original_price", "originalPrice", "INTEGER", false),
        soldStatus("sold_status", "soldStatus", "INTEGER", false),
        productType("product_type", "productType", "INTEGER", false),
        supplier("supplier", "supplier", "VARCHAR", false),
        cardNames("card_names", "cardNames", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table product
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}