package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.Arrays;

public class RefundResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.transaction_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.refund_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.out_refund_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String outRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.settlement_total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer settlementTotalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.refund_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer refundFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.settlement_refund_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer settlementRefundFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.refund_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String refundStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.success_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String successTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.refund_recv_accout
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String refundRecvAccout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.refund_account
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String refundAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.refund_request_source
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String refundRequestSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column refund_result.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.id
     *
     * @return the value of refund_result.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.id
     *
     * @param id the value for refund_result.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.transaction_id
     *
     * @return the value of refund_result.transaction_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.transaction_id
     *
     * @param transactionId the value for refund_result.transaction_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.out_trade_no
     *
     * @return the value of refund_result.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.out_trade_no
     *
     * @param outTradeNo the value for refund_result.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.refund_id
     *
     * @return the value of refund_result.refund_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.refund_id
     *
     * @param refundId the value for refund_result.refund_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.out_refund_no
     *
     * @return the value of refund_result.out_refund_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.out_refund_no
     *
     * @param outRefundNo the value for refund_result.out_refund_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.total_fee
     *
     * @return the value of refund_result.total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.total_fee
     *
     * @param totalFee the value for refund_result.total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.settlement_total_fee
     *
     * @return the value of refund_result.settlement_total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getSettlementTotalFee() {
        return settlementTotalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.settlement_total_fee
     *
     * @param settlementTotalFee the value for refund_result.settlement_total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSettlementTotalFee(Integer settlementTotalFee) {
        this.settlementTotalFee = settlementTotalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.refund_fee
     *
     * @return the value of refund_result.refund_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.refund_fee
     *
     * @param refundFee the value for refund_result.refund_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setRefundFee(Integer refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.settlement_refund_fee
     *
     * @return the value of refund_result.settlement_refund_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getSettlementRefundFee() {
        return settlementRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.settlement_refund_fee
     *
     * @param settlementRefundFee the value for refund_result.settlement_refund_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSettlementRefundFee(Integer settlementRefundFee) {
        this.settlementRefundFee = settlementRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.refund_status
     *
     * @return the value of refund_result.refund_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.refund_status
     *
     * @param refundStatus the value for refund_result.refund_status
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.success_time
     *
     * @return the value of refund_result.success_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.success_time
     *
     * @param successTime the value for refund_result.success_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setSuccessTime(String successTime) {
        this.successTime = successTime == null ? null : successTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.refund_recv_accout
     *
     * @return the value of refund_result.refund_recv_accout
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getRefundRecvAccout() {
        return refundRecvAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.refund_recv_accout
     *
     * @param refundRecvAccout the value for refund_result.refund_recv_accout
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setRefundRecvAccout(String refundRecvAccout) {
        this.refundRecvAccout = refundRecvAccout == null ? null : refundRecvAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.refund_account
     *
     * @return the value of refund_result.refund_account
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getRefundAccount() {
        return refundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.refund_account
     *
     * @param refundAccount the value for refund_result.refund_account
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setRefundAccount(String refundAccount) {
        this.refundAccount = refundAccount == null ? null : refundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.refund_request_source
     *
     * @return the value of refund_result.refund_request_source
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getRefundRequestSource() {
        return refundRequestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.refund_request_source
     *
     * @param refundRequestSource the value for refund_result.refund_request_source
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setRefundRequestSource(String refundRequestSource) {
        this.refundRequestSource = refundRequestSource == null ? null : refundRequestSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column refund_result.create_time
     *
     * @return the value of refund_result.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column refund_result.create_time
     *
     * @param createTime the value for refund_result.create_time
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table refund_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        transactionId("transaction_id", "transactionId", "VARCHAR", false),
        outTradeNo("out_trade_no", "outTradeNo", "VARCHAR", false),
        refundId("refund_id", "refundId", "VARCHAR", false),
        outRefundNo("out_refund_no", "outRefundNo", "VARCHAR", false),
        totalFee("total_fee", "totalFee", "INTEGER", false),
        settlementTotalFee("settlement_total_fee", "settlementTotalFee", "INTEGER", false),
        refundFee("refund_fee", "refundFee", "INTEGER", false),
        settlementRefundFee("settlement_refund_fee", "settlementRefundFee", "INTEGER", false),
        refundStatus("refund_status", "refundStatus", "VARCHAR", false),
        successTime("success_time", "successTime", "VARCHAR", false),
        refundRecvAccout("refund_recv_accout", "refundRecvAccout", "VARCHAR", false),
        refundAccount("refund_account", "refundAccount", "VARCHAR", false),
        refundRequestSource("refund_request_source", "refundRequestSource", "VARCHAR", false),
        createTime("create_time", "createTime", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table refund_result
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}