package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.List;

public class UnifiedOrderRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public UnifiedOrderRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBodyIsNull() {
            addCriterion("body is null");
            return (Criteria) this;
        }

        public Criteria andBodyIsNotNull() {
            addCriterion("body is not null");
            return (Criteria) this;
        }

        public Criteria andBodyEqualTo(String value) {
            addCriterion("body =", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotEqualTo(String value) {
            addCriterion("body <>", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThan(String value) {
            addCriterion("body >", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThanOrEqualTo(String value) {
            addCriterion("body >=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThan(String value) {
            addCriterion("body <", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThanOrEqualTo(String value) {
            addCriterion("body <=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLike(String value) {
            addCriterion("body like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotLike(String value) {
            addCriterion("body not like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyIn(List<String> values) {
            addCriterion("body in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotIn(List<String> values) {
            addCriterion("body not in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyBetween(String value1, String value2) {
            addCriterion("body between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotBetween(String value1, String value2) {
            addCriterion("body not between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("out_trade_no is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("out_trade_no is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("out_trade_no =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("out_trade_no <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("out_trade_no >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("out_trade_no >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("out_trade_no <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("out_trade_no <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("out_trade_no like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("out_trade_no not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("out_trade_no in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("out_trade_no not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("out_trade_no between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("out_trade_no not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNull() {
            addCriterion("total_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNotNull() {
            addCriterion("total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeEqualTo(Integer value) {
            addCriterion("total_fee =", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotEqualTo(Integer value) {
            addCriterion("total_fee <>", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThan(Integer value) {
            addCriterion("total_fee >", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_fee >=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThan(Integer value) {
            addCriterion("total_fee <", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThanOrEqualTo(Integer value) {
            addCriterion("total_fee <=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIn(List<Integer> values) {
            addCriterion("total_fee in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotIn(List<Integer> values) {
            addCriterion("total_fee not in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeBetween(Integer value1, Integer value2) {
            addCriterion("total_fee between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotBetween(Integer value1, Integer value2) {
            addCriterion("total_fee not between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNull() {
            addCriterion("openid is null");
            return (Criteria) this;
        }

        public Criteria andOpenidIsNotNull() {
            addCriterion("openid is not null");
            return (Criteria) this;
        }

        public Criteria andOpenidEqualTo(String value) {
            addCriterion("openid =", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotEqualTo(String value) {
            addCriterion("openid <>", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThan(String value) {
            addCriterion("openid >", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("openid >=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThan(String value) {
            addCriterion("openid <", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLessThanOrEqualTo(String value) {
            addCriterion("openid <=", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidLike(String value) {
            addCriterion("openid like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotLike(String value) {
            addCriterion("openid not like", value, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidIn(List<String> values) {
            addCriterion("openid in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotIn(List<String> values) {
            addCriterion("openid not in", values, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidBetween(String value1, String value2) {
            addCriterion("openid between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andOpenidNotBetween(String value1, String value2) {
            addCriterion("openid not between", value1, value2, "openid");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIsNull() {
            addCriterion("return_code is null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIsNotNull() {
            addCriterion("return_code is not null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeEqualTo(String value) {
            addCriterion("return_code =", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotEqualTo(String value) {
            addCriterion("return_code <>", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeGreaterThan(String value) {
            addCriterion("return_code >", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("return_code >=", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLessThan(String value) {
            addCriterion("return_code <", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLessThanOrEqualTo(String value) {
            addCriterion("return_code <=", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeLike(String value) {
            addCriterion("return_code like", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotLike(String value) {
            addCriterion("return_code not like", value, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeIn(List<String> values) {
            addCriterion("return_code in", values, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotIn(List<String> values) {
            addCriterion("return_code not in", values, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeBetween(String value1, String value2) {
            addCriterion("return_code between", value1, value2, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotBetween(String value1, String value2) {
            addCriterion("return_code not between", value1, value2, "returnCode");
            return (Criteria) this;
        }

        public Criteria andReturnMsgIsNull() {
            addCriterion("return_msg is null");
            return (Criteria) this;
        }

        public Criteria andReturnMsgIsNotNull() {
            addCriterion("return_msg is not null");
            return (Criteria) this;
        }

        public Criteria andReturnMsgEqualTo(String value) {
            addCriterion("return_msg =", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotEqualTo(String value) {
            addCriterion("return_msg <>", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgGreaterThan(String value) {
            addCriterion("return_msg >", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgGreaterThanOrEqualTo(String value) {
            addCriterion("return_msg >=", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgLessThan(String value) {
            addCriterion("return_msg <", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgLessThanOrEqualTo(String value) {
            addCriterion("return_msg <=", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgLike(String value) {
            addCriterion("return_msg like", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotLike(String value) {
            addCriterion("return_msg not like", value, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgIn(List<String> values) {
            addCriterion("return_msg in", values, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotIn(List<String> values) {
            addCriterion("return_msg not in", values, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgBetween(String value1, String value2) {
            addCriterion("return_msg between", value1, value2, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotBetween(String value1, String value2) {
            addCriterion("return_msg not between", value1, value2, "returnMsg");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNull() {
            addCriterion("result_code is null");
            return (Criteria) this;
        }

        public Criteria andResultCodeIsNotNull() {
            addCriterion("result_code is not null");
            return (Criteria) this;
        }

        public Criteria andResultCodeEqualTo(String value) {
            addCriterion("result_code =", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotEqualTo(String value) {
            addCriterion("result_code <>", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThan(String value) {
            addCriterion("result_code >", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeGreaterThanOrEqualTo(String value) {
            addCriterion("result_code >=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThan(String value) {
            addCriterion("result_code <", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLessThanOrEqualTo(String value) {
            addCriterion("result_code <=", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeLike(String value) {
            addCriterion("result_code like", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotLike(String value) {
            addCriterion("result_code not like", value, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeIn(List<String> values) {
            addCriterion("result_code in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotIn(List<String> values) {
            addCriterion("result_code not in", values, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeBetween(String value1, String value2) {
            addCriterion("result_code between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotBetween(String value1, String value2) {
            addCriterion("result_code not between", value1, value2, "resultCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeIsNull() {
            addCriterion("err_code is null");
            return (Criteria) this;
        }

        public Criteria andErrCodeIsNotNull() {
            addCriterion("err_code is not null");
            return (Criteria) this;
        }

        public Criteria andErrCodeEqualTo(String value) {
            addCriterion("err_code =", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotEqualTo(String value) {
            addCriterion("err_code <>", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeGreaterThan(String value) {
            addCriterion("err_code >", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("err_code >=", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeLessThan(String value) {
            addCriterion("err_code <", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeLessThanOrEqualTo(String value) {
            addCriterion("err_code <=", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeLike(String value) {
            addCriterion("err_code like", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotLike(String value) {
            addCriterion("err_code not like", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeIn(List<String> values) {
            addCriterion("err_code in", values, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotIn(List<String> values) {
            addCriterion("err_code not in", values, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeBetween(String value1, String value2) {
            addCriterion("err_code between", value1, value2, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotBetween(String value1, String value2) {
            addCriterion("err_code not between", value1, value2, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesIsNull() {
            addCriterion("err_code_des is null");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesIsNotNull() {
            addCriterion("err_code_des is not null");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesEqualTo(String value) {
            addCriterion("err_code_des =", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotEqualTo(String value) {
            addCriterion("err_code_des <>", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesGreaterThan(String value) {
            addCriterion("err_code_des >", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesGreaterThanOrEqualTo(String value) {
            addCriterion("err_code_des >=", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesLessThan(String value) {
            addCriterion("err_code_des <", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesLessThanOrEqualTo(String value) {
            addCriterion("err_code_des <=", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesLike(String value) {
            addCriterion("err_code_des like", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotLike(String value) {
            addCriterion("err_code_des not like", value, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesIn(List<String> values) {
            addCriterion("err_code_des in", values, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotIn(List<String> values) {
            addCriterion("err_code_des not in", values, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesBetween(String value1, String value2) {
            addCriterion("err_code_des between", value1, value2, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotBetween(String value1, String value2) {
            addCriterion("err_code_des not between", value1, value2, "errCodeDes");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("transaction_id is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("transaction_id is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("transaction_id =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("transaction_id <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("transaction_id >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("transaction_id >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("transaction_id <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("transaction_id <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("transaction_id like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("transaction_id not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("transaction_id in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("transaction_id not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("transaction_id between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("transaction_id not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andBankTypeIsNull() {
            addCriterion("bank_type is null");
            return (Criteria) this;
        }

        public Criteria andBankTypeIsNotNull() {
            addCriterion("bank_type is not null");
            return (Criteria) this;
        }

        public Criteria andBankTypeEqualTo(String value) {
            addCriterion("bank_type =", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeNotEqualTo(String value) {
            addCriterion("bank_type <>", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeGreaterThan(String value) {
            addCriterion("bank_type >", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeGreaterThanOrEqualTo(String value) {
            addCriterion("bank_type >=", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeLessThan(String value) {
            addCriterion("bank_type <", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeLessThanOrEqualTo(String value) {
            addCriterion("bank_type <=", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeLike(String value) {
            addCriterion("bank_type like", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeNotLike(String value) {
            addCriterion("bank_type not like", value, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeIn(List<String> values) {
            addCriterion("bank_type in", values, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeNotIn(List<String> values) {
            addCriterion("bank_type not in", values, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeBetween(String value1, String value2) {
            addCriterion("bank_type between", value1, value2, "bankType");
            return (Criteria) this;
        }

        public Criteria andBankTypeNotBetween(String value1, String value2) {
            addCriterion("bank_type not between", value1, value2, "bankType");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeIsNull() {
            addCriterion("is_subscribe is null");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeIsNotNull() {
            addCriterion("is_subscribe is not null");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeEqualTo(String value) {
            addCriterion("is_subscribe =", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeNotEqualTo(String value) {
            addCriterion("is_subscribe <>", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeGreaterThan(String value) {
            addCriterion("is_subscribe >", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeGreaterThanOrEqualTo(String value) {
            addCriterion("is_subscribe >=", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeLessThan(String value) {
            addCriterion("is_subscribe <", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeLessThanOrEqualTo(String value) {
            addCriterion("is_subscribe <=", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeLike(String value) {
            addCriterion("is_subscribe like", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeNotLike(String value) {
            addCriterion("is_subscribe not like", value, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeIn(List<String> values) {
            addCriterion("is_subscribe in", values, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeNotIn(List<String> values) {
            addCriterion("is_subscribe not in", values, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeBetween(String value1, String value2) {
            addCriterion("is_subscribe between", value1, value2, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andIsSubscribeNotBetween(String value1, String value2) {
            addCriterion("is_subscribe not between", value1, value2, "isSubscribe");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyIsNull() {
            addCriterion("return_code_notify is null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyIsNotNull() {
            addCriterion("return_code_notify is not null");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyEqualTo(String value) {
            addCriterion("return_code_notify =", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyNotEqualTo(String value) {
            addCriterion("return_code_notify <>", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyGreaterThan(String value) {
            addCriterion("return_code_notify >", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyGreaterThanOrEqualTo(String value) {
            addCriterion("return_code_notify >=", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyLessThan(String value) {
            addCriterion("return_code_notify <", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyLessThanOrEqualTo(String value) {
            addCriterion("return_code_notify <=", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyLike(String value) {
            addCriterion("return_code_notify like", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyNotLike(String value) {
            addCriterion("return_code_notify not like", value, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyIn(List<String> values) {
            addCriterion("return_code_notify in", values, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyNotIn(List<String> values) {
            addCriterion("return_code_notify not in", values, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyBetween(String value1, String value2) {
            addCriterion("return_code_notify between", value1, value2, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnCodeNotifyNotBetween(String value1, String value2) {
            addCriterion("return_code_notify not between", value1, value2, "returnCodeNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyIsNull() {
            addCriterion("return_msg_notify is null");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyIsNotNull() {
            addCriterion("return_msg_notify is not null");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyEqualTo(String value) {
            addCriterion("return_msg_notify =", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyNotEqualTo(String value) {
            addCriterion("return_msg_notify <>", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyGreaterThan(String value) {
            addCriterion("return_msg_notify >", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyGreaterThanOrEqualTo(String value) {
            addCriterion("return_msg_notify >=", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyLessThan(String value) {
            addCriterion("return_msg_notify <", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyLessThanOrEqualTo(String value) {
            addCriterion("return_msg_notify <=", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyLike(String value) {
            addCriterion("return_msg_notify like", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyNotLike(String value) {
            addCriterion("return_msg_notify not like", value, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyIn(List<String> values) {
            addCriterion("return_msg_notify in", values, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyNotIn(List<String> values) {
            addCriterion("return_msg_notify not in", values, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyBetween(String value1, String value2) {
            addCriterion("return_msg_notify between", value1, value2, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andReturnMsgNotifyNotBetween(String value1, String value2) {
            addCriterion("return_msg_notify not between", value1, value2, "returnMsgNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyIsNull() {
            addCriterion("result_code_notify is null");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyIsNotNull() {
            addCriterion("result_code_notify is not null");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyEqualTo(String value) {
            addCriterion("result_code_notify =", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyNotEqualTo(String value) {
            addCriterion("result_code_notify <>", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyGreaterThan(String value) {
            addCriterion("result_code_notify >", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyGreaterThanOrEqualTo(String value) {
            addCriterion("result_code_notify >=", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyLessThan(String value) {
            addCriterion("result_code_notify <", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyLessThanOrEqualTo(String value) {
            addCriterion("result_code_notify <=", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyLike(String value) {
            addCriterion("result_code_notify like", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyNotLike(String value) {
            addCriterion("result_code_notify not like", value, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyIn(List<String> values) {
            addCriterion("result_code_notify in", values, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyNotIn(List<String> values) {
            addCriterion("result_code_notify not in", values, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyBetween(String value1, String value2) {
            addCriterion("result_code_notify between", value1, value2, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andResultCodeNotifyNotBetween(String value1, String value2) {
            addCriterion("result_code_notify not between", value1, value2, "resultCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyIsNull() {
            addCriterion("err_code_notify is null");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyIsNotNull() {
            addCriterion("err_code_notify is not null");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyEqualTo(String value) {
            addCriterion("err_code_notify =", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyNotEqualTo(String value) {
            addCriterion("err_code_notify <>", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyGreaterThan(String value) {
            addCriterion("err_code_notify >", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyGreaterThanOrEqualTo(String value) {
            addCriterion("err_code_notify >=", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyLessThan(String value) {
            addCriterion("err_code_notify <", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyLessThanOrEqualTo(String value) {
            addCriterion("err_code_notify <=", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyLike(String value) {
            addCriterion("err_code_notify like", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyNotLike(String value) {
            addCriterion("err_code_notify not like", value, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyIn(List<String> values) {
            addCriterion("err_code_notify in", values, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyNotIn(List<String> values) {
            addCriterion("err_code_notify not in", values, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyBetween(String value1, String value2) {
            addCriterion("err_code_notify between", value1, value2, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotifyNotBetween(String value1, String value2) {
            addCriterion("err_code_notify not between", value1, value2, "errCodeNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyIsNull() {
            addCriterion("err_code_des_notify is null");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyIsNotNull() {
            addCriterion("err_code_des_notify is not null");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyEqualTo(String value) {
            addCriterion("err_code_des_notify =", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyNotEqualTo(String value) {
            addCriterion("err_code_des_notify <>", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyGreaterThan(String value) {
            addCriterion("err_code_des_notify >", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyGreaterThanOrEqualTo(String value) {
            addCriterion("err_code_des_notify >=", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyLessThan(String value) {
            addCriterion("err_code_des_notify <", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyLessThanOrEqualTo(String value) {
            addCriterion("err_code_des_notify <=", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyLike(String value) {
            addCriterion("err_code_des_notify like", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyNotLike(String value) {
            addCriterion("err_code_des_notify not like", value, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyIn(List<String> values) {
            addCriterion("err_code_des_notify in", values, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyNotIn(List<String> values) {
            addCriterion("err_code_des_notify not in", values, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyBetween(String value1, String value2) {
            addCriterion("err_code_des_notify between", value1, value2, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andErrCodeDesNotifyNotBetween(String value1, String value2) {
            addCriterion("err_code_des_notify not between", value1, value2, "errCodeDesNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyIsNull() {
            addCriterion("total_fee_notify is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyIsNotNull() {
            addCriterion("total_fee_notify is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyEqualTo(Integer value) {
            addCriterion("total_fee_notify =", value, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyNotEqualTo(Integer value) {
            addCriterion("total_fee_notify <>", value, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyGreaterThan(Integer value) {
            addCriterion("total_fee_notify >", value, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_fee_notify >=", value, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyLessThan(Integer value) {
            addCriterion("total_fee_notify <", value, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyLessThanOrEqualTo(Integer value) {
            addCriterion("total_fee_notify <=", value, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyIn(List<Integer> values) {
            addCriterion("total_fee_notify in", values, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyNotIn(List<Integer> values) {
            addCriterion("total_fee_notify not in", values, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyBetween(Integer value1, Integer value2) {
            addCriterion("total_fee_notify between", value1, value2, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotifyNotBetween(Integer value1, Integer value2) {
            addCriterion("total_fee_notify not between", value1, value2, "totalFeeNotify");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(String value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(String value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(String value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(String value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(String value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLike(String value) {
            addCriterion("ctime like", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotLike(String value) {
            addCriterion("ctime not like", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<String> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<String> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(String value1, String value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(String value1, String value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNull() {
            addCriterion("utime is null");
            return (Criteria) this;
        }

        public Criteria andUtimeIsNotNull() {
            addCriterion("utime is not null");
            return (Criteria) this;
        }

        public Criteria andUtimeEqualTo(String value) {
            addCriterion("utime =", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotEqualTo(String value) {
            addCriterion("utime <>", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThan(String value) {
            addCriterion("utime >", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeGreaterThanOrEqualTo(String value) {
            addCriterion("utime >=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThan(String value) {
            addCriterion("utime <", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLessThanOrEqualTo(String value) {
            addCriterion("utime <=", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeLike(String value) {
            addCriterion("utime like", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotLike(String value) {
            addCriterion("utime not like", value, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeIn(List<String> values) {
            addCriterion("utime in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotIn(List<String> values) {
            addCriterion("utime not in", values, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeBetween(String value1, String value2) {
            addCriterion("utime between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andUtimeNotBetween(String value1, String value2) {
            addCriterion("utime not between", value1, value2, "utime");
            return (Criteria) this;
        }

        public Criteria andFtimeIsNull() {
            addCriterion("ftime is null");
            return (Criteria) this;
        }

        public Criteria andFtimeIsNotNull() {
            addCriterion("ftime is not null");
            return (Criteria) this;
        }

        public Criteria andFtimeEqualTo(String value) {
            addCriterion("ftime =", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeNotEqualTo(String value) {
            addCriterion("ftime <>", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeGreaterThan(String value) {
            addCriterion("ftime >", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeGreaterThanOrEqualTo(String value) {
            addCriterion("ftime >=", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeLessThan(String value) {
            addCriterion("ftime <", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeLessThanOrEqualTo(String value) {
            addCriterion("ftime <=", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeLike(String value) {
            addCriterion("ftime like", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeNotLike(String value) {
            addCriterion("ftime not like", value, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeIn(List<String> values) {
            addCriterion("ftime in", values, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeNotIn(List<String> values) {
            addCriterion("ftime not in", values, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeBetween(String value1, String value2) {
            addCriterion("ftime between", value1, value2, "ftime");
            return (Criteria) this;
        }

        public Criteria andFtimeNotBetween(String value1, String value2) {
            addCriterion("ftime not between", value1, value2, "ftime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table unified_order_record
     *
     * @mbg.generated do_not_delete_during_merge Thu Dec 06 16:21:59 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table unified_order_record
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}