package com.marquess.demo.model;

import java.util.ArrayList;
import java.util.Arrays;

public class UnifiedOrderRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.body
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.openid
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.return_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String returnCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.return_msg
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String returnMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.result_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String resultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.err_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String errCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.err_code_des
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String errCodeDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.transaction_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.bank_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String bankType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.is_subscribe
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String isSubscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.return_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String returnCodeNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.return_msg_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String returnMsgNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.result_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String resultCodeNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.err_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String errCodeNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.err_code_des_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String errCodeDesNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.total_fee_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private Integer totalFeeNotify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.ctime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.utime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String utime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unified_order_record.ftime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    private String ftime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.id
     *
     * @return the value of unified_order_record.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.id
     *
     * @param id the value for unified_order_record.id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.body
     *
     * @return the value of unified_order_record.body
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.body
     *
     * @param body the value for unified_order_record.body
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setBody(String body) {
        this.body = body == null ? null : body.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.out_trade_no
     *
     * @return the value of unified_order_record.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.out_trade_no
     *
     * @param outTradeNo the value for unified_order_record.out_trade_no
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.total_fee
     *
     * @return the value of unified_order_record.total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.total_fee
     *
     * @param totalFee the value for unified_order_record.total_fee
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.openid
     *
     * @return the value of unified_order_record.openid
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.openid
     *
     * @param openid the value for unified_order_record.openid
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.return_code
     *
     * @return the value of unified_order_record.return_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.return_code
     *
     * @param returnCode the value for unified_order_record.return_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.return_msg
     *
     * @return the value of unified_order_record.return_msg
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.return_msg
     *
     * @param returnMsg the value for unified_order_record.return_msg
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.result_code
     *
     * @return the value of unified_order_record.result_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.result_code
     *
     * @param resultCode the value for unified_order_record.result_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.err_code
     *
     * @return the value of unified_order_record.err_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.err_code
     *
     * @param errCode the value for unified_order_record.err_code
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.err_code_des
     *
     * @return the value of unified_order_record.err_code_des
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.err_code_des
     *
     * @param errCodeDes the value for unified_order_record.err_code_des
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes == null ? null : errCodeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.transaction_id
     *
     * @return the value of unified_order_record.transaction_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.transaction_id
     *
     * @param transactionId the value for unified_order_record.transaction_id
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.bank_type
     *
     * @return the value of unified_order_record.bank_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.bank_type
     *
     * @param bankType the value for unified_order_record.bank_type
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setBankType(String bankType) {
        this.bankType = bankType == null ? null : bankType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.is_subscribe
     *
     * @return the value of unified_order_record.is_subscribe
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getIsSubscribe() {
        return isSubscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.is_subscribe
     *
     * @param isSubscribe the value for unified_order_record.is_subscribe
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setIsSubscribe(String isSubscribe) {
        this.isSubscribe = isSubscribe == null ? null : isSubscribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.return_code_notify
     *
     * @return the value of unified_order_record.return_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getReturnCodeNotify() {
        return returnCodeNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.return_code_notify
     *
     * @param returnCodeNotify the value for unified_order_record.return_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setReturnCodeNotify(String returnCodeNotify) {
        this.returnCodeNotify = returnCodeNotify == null ? null : returnCodeNotify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.return_msg_notify
     *
     * @return the value of unified_order_record.return_msg_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getReturnMsgNotify() {
        return returnMsgNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.return_msg_notify
     *
     * @param returnMsgNotify the value for unified_order_record.return_msg_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setReturnMsgNotify(String returnMsgNotify) {
        this.returnMsgNotify = returnMsgNotify == null ? null : returnMsgNotify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.result_code_notify
     *
     * @return the value of unified_order_record.result_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getResultCodeNotify() {
        return resultCodeNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.result_code_notify
     *
     * @param resultCodeNotify the value for unified_order_record.result_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setResultCodeNotify(String resultCodeNotify) {
        this.resultCodeNotify = resultCodeNotify == null ? null : resultCodeNotify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.err_code_notify
     *
     * @return the value of unified_order_record.err_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getErrCodeNotify() {
        return errCodeNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.err_code_notify
     *
     * @param errCodeNotify the value for unified_order_record.err_code_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setErrCodeNotify(String errCodeNotify) {
        this.errCodeNotify = errCodeNotify == null ? null : errCodeNotify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.err_code_des_notify
     *
     * @return the value of unified_order_record.err_code_des_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getErrCodeDesNotify() {
        return errCodeDesNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.err_code_des_notify
     *
     * @param errCodeDesNotify the value for unified_order_record.err_code_des_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setErrCodeDesNotify(String errCodeDesNotify) {
        this.errCodeDesNotify = errCodeDesNotify == null ? null : errCodeDesNotify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.total_fee_notify
     *
     * @return the value of unified_order_record.total_fee_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public Integer getTotalFeeNotify() {
        return totalFeeNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.total_fee_notify
     *
     * @param totalFeeNotify the value for unified_order_record.total_fee_notify
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setTotalFeeNotify(Integer totalFeeNotify) {
        this.totalFeeNotify = totalFeeNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.ctime
     *
     * @return the value of unified_order_record.ctime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.ctime
     *
     * @param ctime the value for unified_order_record.ctime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setCtime(String ctime) {
        this.ctime = ctime == null ? null : ctime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.utime
     *
     * @return the value of unified_order_record.utime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getUtime() {
        return utime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.utime
     *
     * @param utime the value for unified_order_record.utime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setUtime(String utime) {
        this.utime = utime == null ? null : utime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unified_order_record.ftime
     *
     * @return the value of unified_order_record.ftime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public String getFtime() {
        return ftime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unified_order_record.ftime
     *
     * @param ftime the value for unified_order_record.ftime
     *
     * @mbg.generated Thu Dec 06 16:21:59 CST 2018
     */
    public void setFtime(String ftime) {
        this.ftime = ftime == null ? null : ftime.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table unified_order_record
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        id("id", "id", "BIGINT", false),
        body("body", "body", "VARCHAR", false),
        outTradeNo("out_trade_no", "outTradeNo", "VARCHAR", false),
        totalFee("total_fee", "totalFee", "INTEGER", false),
        openid("openid", "openid", "VARCHAR", false),
        returnCode("return_code", "returnCode", "VARCHAR", false),
        returnMsg("return_msg", "returnMsg", "VARCHAR", false),
        resultCode("result_code", "resultCode", "VARCHAR", false),
        errCode("err_code", "errCode", "VARCHAR", false),
        errCodeDes("err_code_des", "errCodeDes", "VARCHAR", false),
        transactionId("transaction_id", "transactionId", "VARCHAR", false),
        bankType("bank_type", "bankType", "VARCHAR", false),
        isSubscribe("is_subscribe", "isSubscribe", "VARCHAR", false),
        returnCodeNotify("return_code_notify", "returnCodeNotify", "VARCHAR", false),
        returnMsgNotify("return_msg_notify", "returnMsgNotify", "VARCHAR", false),
        resultCodeNotify("result_code_notify", "resultCodeNotify", "VARCHAR", false),
        errCodeNotify("err_code_notify", "errCodeNotify", "VARCHAR", false),
        errCodeDesNotify("err_code_des_notify", "errCodeDesNotify", "VARCHAR", false),
        totalFeeNotify("total_fee_notify", "totalFeeNotify", "INTEGER", false),
        ctime("ctime", "ctime", "VARCHAR", false),
        utime("utime", "utime", "VARCHAR", false),
        ftime("ftime", "ftime", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "\"";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table unified_order_record
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}